[env:ch552]
platform = https://github.com/DeqingSun/ch55xduino.git
board = ch552
framework = arduino

; 上传配置
upload_protocol = usbasp
upload_flags = 
    -F

; 编译选项
build_flags = 
    -DCLOCK_FREQ=24000000L
    -DUSB_VID=0x1A86
    -DUSB_PID=0x5537

; 串口监控
monitor_speed = 115200
; 根据实际端口修改
; monitor_port = COM3

; 库依赖
lib_deps = 
    ; 本地DS18B20库在lib文件夹中

; 调试配置
build_type = debug
