[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_port = COM12
upload_speed = 115200
upload_resetmethod = nodemcu
; 仅编译 C++ wrapper（避免 .c 文件被当作 C 编译，进而无法包含 Arduino/WiFi 头）
build_src_filter =
    -<*>
    +<esp8266/>
build_flags =
    -Isrc
